### PR TITLE
Revert "Require peer certificate to be present when ca_cert_file is s…

### PR DESCRIPTION
**Pull request by mattklein123**
…et (#648)"

This reverts commit 168764479000909930a0c9764a43904b4e276fef.

### CODE REVIEW

**Comment by mattklein123** [comment]
@lookuptable unfortunately we need to revert this. I forgot about  a use case we have where we actually do need to accept SSL connections even when CA is specified. This is because we have an SSL endpoint where sometimes people have certs and sometimes we don't and we have whitelisting logic that handles this. Can you redo this change and make the behavior optional. I don't really care if you default to on, but we need to be able to turn the behavior off. This is for use with our client SSL auth filter: https://github.com/lyft/envoy/blob/master/source/common/filter/auth/client_ssl.cc

**Comment by mattklein123** [comment]
@lyft/network-team

**Comment by RomanDzhabarov** [comment]
@mattklein123 unless urgent, i'll do deploy on monday

**Comment by mattklein123** [comment]
@RomanDzhabarov not urgent. I might be able to do one Sunday. But I think we can wait till Monday.

**Comment by RomanDzhabarov** [comment]
Yup, sounds good

**Pull request merged**
