### PR TITLE
build: update build image to 98a1276049a3cf4bebc6a0343217444a8675baf8

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
@htuch

**Comment by htuch** [comment]
LGTM, let me know if there are any issues.

**Comment by mattklein123** [comment]
@htuch looks like coverage is failing: https://travis-ci.org/lyft/envoy/jobs/221897553

**Comment by htuch** [comment]
Will look into this early tomorrow if that's OK.

**Comment by mattklein123** [comment]
Yup no problem.

**Comment by mattklein123** [comment]
Closing in favor of https://github.com/lyft/envoy/pull/769

**Pull request closed without merging**
