### PR TITLE
ci: add clang head/5.0 to CI image

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
@htuch

**Comment by mattklein123** [comment]
Let me try to see what they have in the repo.

**Comment by mattklein123** [comment]
```
mklein@localhost:~/Source/envoy-private/envoy/ci/build_container$ apt-cache madison clang-4.0
 clang-4.0 | 1:4.0~svn301550-1~exp1 | http://apt.llvm.org/xenial llvm-toolchain-xenial-4.0/main amd64 Packages
```

@htuch ^

I don't think multiple versions are available, so I think we are stuck. What do you want to do? Optimally I would agree it would be pinned, but not sure how to do that unless we run our own PPA somewhere.

**Comment by htuch** [comment]
OK, let's go with this for now, and be prepared to suspect compiler drift when the ASAN/MSAN/TSAN runs break.

**Comment by htuch** [comment]
@mattklein123 please let me know when you have a Docker image ID for me to consume, I'll add the Travis build targets for TSAN/MSAN/ASAN.

**Pull request merged**
