### PR TITLE
docs: add info on osx docker builds

### PR DESCRIPTION
**Pull request by RyanMcG**
id -u and id -g was not finding a matching user in the container which caused issues running various commands.

### CODE REVIEW

**Comment by mattklein123** [comment]
Running as root universally should not be necessary, but I don't know specifically why @htuch added the user stuff in the first place. Perhaps he can comment.

**Comment by htuch** [comment]
If you run as root, the build/ and generated/ trees on the bind mounted volume (i.e. your Envoy directory) are owned by root. This makes removing them or modifying files a pain. I guess we could solve the problem by umask as well, I'm a bit surprised this is an issue though, it works fine for me with the usual build process.

Can you either dig into this or provide an alternative command that doesn't leave around artifacts that can't be removed without a sudo? Thanks.

**Comment by RyanMcG** [comment]
Well, I am not getting root owned artifacts in my bound dir, so that's odd. I think the root of the problem is that the my laptop's users are not synchronized with the containers. Just differences from running on a Mac?

**Comment by htuch** [comment]
Yeah, it looks like the treatment of ownership and users with bind mounts is completely different on Docker OS X, https://docs.docker.com/docker-for-mac/osxfs/. It seems fine to run as root in terms of build artifacts as you note, and using the invoking user's UID/GID doesn't help any. On Linux, it's still useful to do this though as UID/GID are shared.

Can you change your PR to provide an alternative for OS X and a one line summary for why we do it one way on Linux and another on OS X?

**Comment by moderation** [comment]
FWIW I get root owned artifacts on Xubuntu 16:10 using the Docker container build method. There is some possibility I got the steps outlined at https://docs.docker.com/engine/installation/linux/linux-postinstall/#/manage-docker-as-a-non-root-user incorrect.

**Comment by RyanMcG** [comment]
@htuch that sounds like the issue then. I'll try to update the instructions here.

**Comment by htuch** [comment]
Thanks, LGTM.

**Comment by RyanMcG** [comment]
@htuch @mattklein123 @moderation updated. Let me know what you think.

**Comment by moderation** [comment]
@RyanMcG Works great! Really good not to have to sudo remove the build directory before rebuilding. Thanks.

**Pull request merged**
