### PR TITLE
bazel: minor fixes for consuming projects

### PR DESCRIPTION
**Pull request by mattklein123**
Thanks to @htuch for debugging help.

### CODE REVIEW

**Comment by htuch** [comment]
LGTM. Do the integration tests with JSON pass with this?

**Comment by mattklein123** [comment]
No not yet, I'm still debugging.

**Comment by mattklein123** [comment]
@htuch I have everything working for Lyft private. I just added a more obvious failure in environment  file substitute if a file can't be opened. Easier to debug.

**Comment by htuch** [comment]
LGTM.

**Pull request merged**
