### PR TITLE
swap NOT_IMPLEMENTED for NOT_REACHED where appropriate

### PR DESCRIPTION
**Pull request by mattklein123**
Fixes https://github.com/lyft/envoy/issues/590

### CODE REVIEW

**Comment by mattklein123** [comment]
@lyft/network-team

**Comment by PiotrSikora** [comment]
You could move the `NOT_REACHED` into `switch` statement in most of the cases, i.e.:

    switch (...) {
    ...
    default:
      NOT_REACHED
    }

Also, is there any reason why `NOT_REACHED` is implemented as log entry instead of `EnvoyException`?

**Comment by htuch** [comment]
I think the idea is that the compiler was too dumb to figure out all cases had been covered, but I'm still surprised this is the case. I wonder if we're missing some flags.

**Comment by mattklein123** [comment]
> You could move the NOT_REACHED into switch statement in most of the cases

Yes, per @htuch the compiler is too stupid to realize that all cases are covered and the function will always return. It's better to not have a default in a switch statement if not necessary because the compiler will error that not all cases are covered. This is why I didn't add default.

> Also, is there any reason why NOT_REACHED is implemented as log entry instead of EnvoyException

It logs and then calls abort(). This is better than an exception because it guarantees immediate core dump where an exception might be caught.

@PiotrSikora lmk if these explanations satisfy you.

**Comment by PiotrSikora** [comment]
> It logs and then calls abort(). This is better than an exception because it guarantees immediate core dump where an exception might be caught.

@mattklein123 That makes sense, thanks!

**Pull request merged**
