### PR TITLE
bazel: upgrade cc_configure.bzl for Bazel 0.5.2.

### PR DESCRIPTION
**Pull request by htuch**
* Previous cc_configure.bzl was somewhat stale, didn't provide required variable substitutions, thus
  breaking build.

* Explicitly disabled OS X and Windows build support with fail() messages indicating we need to
  revisit.

* Updated requirements to specify Bazel version.

### CODE REVIEW

**Comment by mattklein123** [comment]
Is it possible to split into 2 commits so that we can see what the delta is on top of the default files? Otherwise can't really review. Not a big deal but if you feel like it.

**Comment by htuch** [comment]
Splitting will break the existing build. How about adding a `.diff` next to each file and check that in?

**Comment by mattklein123** [comment]
Sorry I didn't mean to split into 2 PRs, just 2 commits in this PR so I can look at just delta. Diffs are fine.

**Comment by htuch** [comment]
Close/reopen to deal with a timeout in bazel.release. Seems we got unlucky.

**Comment by htuch** [comment]
@mattklein123 Can I get re-approval? Thanks.

**Pull request merged**
