### PR TITLE
Add grpc-httpjson-transcoding dependency

### PR DESCRIPTION
**Pull request by lizan**
for #501

### CODE REVIEW

**Comment by htuch** [comment]
Looks good, but can you add a description in the commit message of what you're adding? You'll have to wait for the merge of #1063 for this and add the updated CI hash when the Docker image is rebuilt.

Also, I wonder if this technically becomes an additional dependency - we're not going to be consuming this as prebuilts, but building each time in CI and developer build, since this is Bazel native. @mattklein123 WDYT?

**Comment by mattklein123** [comment]
Yeah, I was concerned about that as well (no prebuilt). Not sure if we should have a hard rule on this or decide on a case by case basis? How long will it take to build this extra code? I assume not that long?

**Comment by lizan** [comment]
Having another build tool support or invoking bazel inside the deps rule doesn't sound right. The library itself is tiny (~5k lines of code), and it compiles in a few seconds. Unless you're changing its source or compiler options, bazel will cache it so it won't be time consuming for developer builds.

**Comment by lizan** [comment]
@htuch What description are you looking for? The subject is already in commit message. 

Yes I will wait #1063 to confirm if the library will build on the CI images, but since there is no real code yet, it doesn't breaks CI.

**Comment by htuch** [comment]
@lizan Explain what these libraries actually do in the commit message, not just why they are being imported.

**Comment by lizan** [comment]
@htuch done

**Pull request merged**
