### PR TITLE
build: don't sanitize vptr for gcc asan runs

### PR DESCRIPTION
**Pull request by mattklein123**

### CODE REVIEW

**Comment by mattklein123** [comment]
@htuch @dnoe @hennna for reasons I don't understand this just started to crap out with some of @hennna recent test parameterize changes. I don't really want to look into it much more. i think this is OK since it matches how we run clang sanitize also.

**Comment by mattklein123** [comment]
I guess larger question is could we merge the ASAN configs? Is there any reason to have different ones? The clang one seems like a superset.

**Comment by hennna** [comment]
Are the error messages that you are seeing of the form:

`test/test_common/utility.cc:55:37: runtime error: variable length array bound evaluates to non-positive value 0`

Using git reset, I'm also seeing the same messages prior to the parameterization commits.

**Comment by hennna** [comment]
I'm seeing: 

`x86_64-grtev4-linux-gnu-g++: error: unrecognized argument to -fsanitize= option: 'vptr'`
`x86_64-grtev4-linux-gnu-g++: error: unrecognized command line option '-fno-sanitize-recover=all'`

with gcc 4.8.4 and clang-asan. Seems that it was added in gcc 5.

**Comment by mattklein123** [comment]
@hennna @htuch sorry should have been more clear on the problem. It actually crashes on GCC 5.4 during some type of RTTI lookup (I think):

```
==4476==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x2af6e0727ca3 bp 0x2af6e0970a18 sp 0x7ffc26e7b5b0 T0)
    #0 0x2af6e0727ca2  (/usr/lib/x86_64-linux-gnu/libubsan.so.0+0xbca2)
    #1 0x2af6e07269e2  (/usr/lib/x86_64-linux-gnu/libubsan.so.0+0xa9e2)
    #2 0x2af6e0727170 in __ubsan_handle_dynamic_type_cache_miss (/usr/lib/x86_64-linux-gnu/libubsan.so.0+0xb170)
    #3 0x45a441 in Envoy::IntegrationTest::IntegrationTest() (/root/.cache/bazel/_bazel_root/335a8bf8eaf06ac7491f49930df2edb0/execroot/envoy-private/bazel-out/local-dbg/bin/external/envoy/test/integration/integration_test+0x45a441)
    #4 0x45b820 in Envoy::IntegrationTest_RouterNotFound_Test::IntegrationTest_RouterNotFound_Test() (/root/.cache/bazel/_bazel_root/335a8bf8eaf06ac7491f49930df2edb0/execroot/envoy-private/bazel-out/local-dbg/bin/external/envoy/test/integration/integration_test+0x45b820)
    #5 0x4d2637 in testing::internal::ParameterizedTestFactory<Envoy::IntegrationTest_RouterNotFound_Test>::CreateTest() (/root/.cache/bazel/_bazel_root/335a8bf8eaf06ac7491f49930df2edb0/execroot/envoy-private/bazel-out/local-dbg/bin/external/envoy/test/integration/integration_test+0x4d2637)
    #6 0x1b4c187 in testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2402
    #7 0x1b4c187 in testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2438
    #8 0x1b442ed in testing::TestInfo::Run() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2649
    #9 0x1b44564 in testing::TestInfo::Run() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2631
    #10 0x1b44564 in testing::TestCase::Run() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2774
    #11 0x1b450a4 in testing::TestCase::Run() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:4687
    #12 0x1b450a4 in testing::internal::UnitTestImpl::RunAllTests() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:4649
    #13 0x1b4c4e7 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2402
    #14 0x1b4c4e7 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:2438
    #15 0x1b446c2 in testing::UnitTest::Run() /code/envoy-private/generated/thirdparty_deps/googletest.dep.build/googletest-release-1.8.0/googletest/src/gtest.cc:4257
    #16 0x18e044a in RUN_ALL_TESTS() external/envoy/ci/prebuilt/thirdparty_build/include/gtest/gtest.h:2233
    #17 0x18e08b7 in Envoy::TestRunner::RunTests(int, char**) external/envoy/test/test_runner.h:33
    #18 0x18de56c in main external/envoy/test/main.cc:33
    #19 0x2af6e1890f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
    #20 0x41cb6c  (/root/.cache/bazel/_bazel_root/335a8bf8eaf06ac7491f49930df2edb0/execroot/envoy-private/bazel-out/local-dbg/bin/external/envoy/test/integration/integration_test+0x41cb6c)
```

This seems to happen on all of the parameterized integration tests. I guess if all the settings are not the same on GCC < 5, I will just keep them separate from now and merge this.

**Pull request merged**
