### PR TITLE
test: setup script refactor

### PR DESCRIPTION
**Pull request by mattklein123**
Slight refactor to allow setup scripts to be also called from private
code.

### CODE REVIEW

**Comment by mattklein123** [comment]
@htuch we need this to get our private tests working. I think this should be OK.

**Comment by htuch** [comment]
LGTM.

**Comment by htuch** [comment]
Actually, can you push the mkdir to the scripts themselves, since I'll be
only invoking them from Bazel.

**Comment by mattklein123** [comment]
@htuch updated

**Comment by htuch** [comment]
LGTM

**Pull request merged**
