### PR TITLE
Directly depend on fmtlib for fmt::format

### PR DESCRIPTION
**Pull request by kmyerson**
-updated build SHA to incorporate spdlog update
-include fmtlib directly in files where spdlog was included in order to use fmt::format, and remove the spdlog include
-edit associated BUILD files to add fmtlib as an external_dep

#975

### CODE REVIEW

**Comment by mattklein123** [comment]
@kmyerson did you already sign the CLA? I'm confused how your previous PRs got in. I don't see you in there now.

**Comment by mattklein123** [comment]
Yeah +1 to just putting it in base like we do for spdlog, then we only have to add the include and not edit bazel files...

**Comment by kmyerson** [comment]
OK, I'll make that change

**Comment by mattklein123** [comment]
@kmyerson looks good. Thank you. FYI in the future once you open a PR please don't rebase it, just merge master and push new commits. This makes it easier to review.

**Pull request merged**
