### PR TITLE
Revert "ci: add clang-format-5.0"

### PR DESCRIPTION
**Pull request by htuch**
Reverts lyft/envoy#1205. This broke fix_format etc., since it removes clang-format-3.6. We should probably add a CI with the changes to the various scripts and format changes.

### CODE REVIEW

**Comment by mattklein123** [comment]
Is this revert really needed? We should be able to do 2 stage breaking changes like this since we pin the build image SHA.

**Comment by htuch** [comment]
CI is fine, but it's a bit disruptive to have folks unable to run `fix_format` etc. I have a better solution though, let's get `run_envoy_docker` to pick the CI hash by default. I'll put out a PR in a min.

**Comment by mattklein123** [comment]
Yes, agreed, by default run_envoy_docker should use the pinned SHA unless overriden.

**Comment by htuch** [comment]
Obsoleted by #1211.

**Pull request closed without merging**
