### PR TITLE
bazel: document some tips for debug and build performance (#415).

### PR DESCRIPTION
**Pull request by htuch**

### CODE REVIEW

**Comment by mattklein123** [comment]
As long as you are feeling the doc urge, can we add a few other very common ones like --test_args and --test_output ? Not sure what else might be useful.

**Comment by dnoe** [comment]
Discussion of both --strategy=TestRunner=standalone (an option which I find to have somewhat confusing syntax...) and controlling cached test results might be good.

It might also be good to have something that discusses when in theory "bazel clean" is required, and what the --expunge option adds to clean.

**Comment by mattklein123** [comment]
Also perhaps a short discussion on bazel.rc files? I was going to figure out today how to have a personal bazel.rc file that somehow gets merged with the one in tools/bazel.rc.

**Comment by htuch** [comment]
I'll add the sandbox, clean, `--test_output` doco. The rest I feel is better addressed in the Bazel docs (e.g. bazel.rc), but we can add a link if you'd like somewhere.

**Comment by mattklein123** [comment]
> I'll add the sandbox, clean, --test_output doco. The rest I feel is better addressed in the Bazel docs (e.g. bazel.rc), but we can add a link if you'd like somewhere.

Whatever you think is best. Even linking to the relevant sections of bazel docs is fine. bazel has so many options that to a newcomer just knowing the options to look at it is great.

**Pull request merged**
