### PR TITLE
ssl: remove openssl threading code if using boringssl

### PR DESCRIPTION
**Pull request by mattklein123**
boringssl has internal support for threading.

### CODE REVIEW

**Comment by mattklein123** [comment]
@lyft/network-team @PiotrSikora

**Comment by PiotrSikora** [comment]
Both: `CRYPTO_set_id_callback()` and `CRYPTO_set_locking_callback()` are no-op in BoringSSL, so this doesn't change much at runtime.

However, if you want to remove dead code, then `OpenSSL_add_all_algorithms()`, `SSL_load_error_strings()` and `RAND_poll()` are also no-op in BoringSSL.

**Comment by mattklein123** [comment]
I just noticed it in the coverage build so just deleting dead code. I will fix it up to include the other functions you mention.

**Comment by mattklein123** [comment]
@PiotrSikora updated

**Pull request merged**
