### PR TITLE
Converting a bunch of normal mocks to StrictMock

### PR DESCRIPTION
**Pull request by alyssawilk**
Changing all non-pointer not-nice mocks over to strict mocks.  This reduces the odds that changes will cause silent mock spam because now it will cause test failures intead.

The one exemption is this doesn't cover unique pointers because my various passes at sed didn't pick "new namepsace::MockFoo"
@dnoe mind proofing this one unless @mattklein123 thinks it's more trouble than it's worth?

### CODE REVIEW

**Comment by dnoe** [comment]
I'm happy to review it unless @mattklein123 has a reason to avoid doing this - say the word.

**Comment by mattklein123** [comment]
I'm not opposed to this, though I wonder if a better solution would be to do a PR to gmock so that we can set a flag that fails on warning? That seems better to me.

**Comment by mattklein123** [comment]
@alyssawilk should we close this and wait to use https://github.com/google/googletest/pull/1189 when it lands?

**Comment by alyssawilk** [comment]
I am perhaps less optimistic about  google/googletest#1189  but I can
always reopen this if that bounces :-P

**Pull request closed without merging**
