### PR TITLE
http filter: remove reset callback and introduce onDestroy()

### PR DESCRIPTION
**Pull request by mattklein123**
Previously, if an intermediate filter ends a stream without need
of a reset, further filters would have no way of knowing that and
could not clean up properly. This commit is a breaking change to
the filter API (though trivial in most cases). We remove filter
reset callback registration, and replace it with an onDestroy()
method that is called in all cases. Filters must clean up all
async processing in the onDestroy() callback. This approach is
simpler to understand but also has the benefit of increasing
performance because we no longer have to manage a doubly linked
list and allocate space for the callbacks.

Fixes https://github.com/lyft/envoy/issues/947

### CODE REVIEW

**Comment by mattklein123** [comment]
@lizan this will fix your other issue

@lizan @kyessenov @PiotrSikora this is a breaking change for the filter API. Mixer filter will need a fix (though it's trivial).

@lyft/network-team

**Comment by mattklein123** [comment]
This change is a little scary so going to smoke test it in a bit and will report back. Ready for review though.

**Comment by mattklein123** [comment]
@lyft/network-team smoke test looks good. Please review.

**Comment by lizan** [comment]
@mattklein123 Thanks! I already confirmed this works in transcoding filter.

**Pull request merged**
