### PR TITLE
"verify_subject_alt_name" should accept an array of strings

### PR DESCRIPTION
**Pull request by lookuptable**
This commit cleans up a few leftovers from #559 .

### CODE REVIEW

**Comment by lookuptable** [comment]
CC @myidpt @wattli

**Comment by wattli** [comment]
LGTM, but I can't approve it.

**Comment by lookuptable** [comment]
@mattklein123 PTAL

BTW is there any existing test cases for config_schemas.cc? If yes can you please point me to the test file?

**Comment by mattklein123** [comment]
@ccaraman can you take a look at this? I'm a little confused how this passed tests even without the schema change?

**Comment by mattklein123** [comment]
@lookuptable please sign CLA also

**Comment by lookuptable** [comment]
@mattklein123 Signed!

**Comment by ccaraman** [comment]
@mattklein123 It passed because the SSLContexts are checked in two places Json::Schema::LISTENER_SCHEMA and Json::Schema::CLUSTER_SCHEMA. 
 
A more complete fix would be to pull the SSLContext into its own schema and move the check into https://github.com/lyft/envoy/blob/9dcac8ca111ecc8da059d1f8d42eb766b44bacd6/source/common/ssl/context_config_impl.cc#L17 I can do this later this week. 

@lookuptable No, we don't have tests for explicit tests for our schemas other than some places where we load a config that we expect to fail. I've added https://github.com/lyft/envoy/issues/572

**Comment by mattklein123** [comment]
Yes, but for the change to configgen.py, how did that pass tests previously. That is related to upstream. That should generate a config that does not load. Do we not test that case in the example config tests?

**Comment by mattklein123** [comment]
@lookuptable it's not perfect, but you should be able to add a test for a listener that sets verify_subject_alt_name like here: https://github.com/lyft/envoy/blob/master/test/server/configuration_impl_test.cc#L124

I'm guessing in the configgen.py case, we just don't generate an example config with dynamo in it, since I know I fixed this case in our internal configs.

**Pull request merged**
