### PR TITLE
ci: enable bazel.coverage.

### PR DESCRIPTION
**Pull request by htuch**
This buys us 4 things:

1. We verify that Bazel test rules aren't being omitted as new tests and code are added.

2. We verify that the single test binary continues to work.

3. We verify that a non-consuming project build continues to work.

4. We see how long bazel.coverage takes on travis.ci in practice.

### CODE REVIEW

**Comment by mattklein123** [comment]
Can you merge master to get this passing tests. Should we just kill cmake coverage? Not sure if it's work keeping that around and using a build slot. I guess maybe the params are not quite the same yet, but not sure if it matters exactly.

**Comment by htuch** [comment]
Merged, agree, disabled cmake coverage.

**Comment by mattklein123** [comment]
I notice that the job is cloning your protobuf git repo: 
https://travis-ci.org/lyft/envoy/jobs/221753559

Shouldn't that already be included in the build image?

**Comment by htuch** [comment]
I've fixed it. It was a result of the `bazel query` being executed in the source, not build directory, and pulling in that `WORKSPACE`, rather than the CI one.

**Pull request merged**
